export const FETCH_ALL_DATA = "FETCH_ALL_DATA"
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const DELETE_CURRENT_USER = "DELETE_CURRENT_USER"
export const CREATE_NEW_USER = "CREATE_NEW_USER"