export const FETCH_ALL_DATA = "FETCH_ALL_DATA"
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const DELETE_CURRENT_USER = "DELETE_CURRENT_USER"
export const CREATE_NEW_USER = "CREATE_NEW_USER"
export const UPDATE_LAST_MESSAGE = "UPDATE_LAST_MESSAGE"

export const FETCH_ALL_MESSAGES = "FETCH_ALL_MESSAGES"
export const ACTIVE_CHAT_ROOM = "ACTIVE_CHAT_ROOM"
export const CREATE_NEW_MESSAGE = "CREATE_NEW_MESSAGE"